### PR TITLE
update to tag 2.12

### PR DESCRIPTION
**Pull request by nolyn**

### CODE REVIEW

**Comment by hfiguiere** [comment]
It's probably a good time to update to a runtime that is not EOL, like `5.15-21.08`

**Comment by hfiguiere** [comment]
Also you should add `--device=dri` in the finish args so that that video accelaration work.

**Comment by nolyn** [comment]
@hfiguiere thanks, I'll have a look at it. an unrelated question, maybe you know. the developer of YUView (https://github.com/ChristianFeldmann) would like to get write access here as well. I wrote about it to flathub-admins-owner@lists.freedesktop.org, but so far nothing. Maybe it just takes time ...

**Comment by hfiguiere** [comment]
> @hfiguiere thanks, I'll have a look at it. an unrelated question, maybe you know. the developer of YUView (https://github.com/ChristianFeldmann) would like to get write access here as well. I wrote about it to [flathub-admins-owner@lists.freedesktop.org](mailto:flathub-admins-owner@lists.freedesktop.org), but so far nothing. Maybe it just takes time ...

For write access, @barthalion or @nedrichards can help.

**Comment by nolyn** [comment]
bot, build de.rwth_aachen.ient.YUView

**Pull request merged**
